"""Cria tabela plano_vacinal_logs para auditoria

Revision ID: 93951cb55e9c
Revises: 
Create Date: 2025-07-20 22:12:33.997169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93951cb55e9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plano_vacinal_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('paciente_data_nascimento', sa.Date(), nullable=False),
    sa.Column('paciente_sexo', sa.String(length=20), nullable=True),
    sa.Column('numero_doses_recebidas', sa.Integer(), nullable=True),
    sa.Column('request_input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plano_vacinal_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plano_vacinal_logs_paciente_data_nascimento'), ['paciente_data_nascimento'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plano_vacinal_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plano_vacinal_logs_paciente_data_nascimento'))

    op.drop_table('plano_vacinal_logs')
    # ### end Alembic commands ###
